### ISSUE TITLE
Full height

### ISSUE THREAD

**Issue by maverick74** [Intika-Linux-Plasmoid/plasmoid-notifications-full#1]
I would like to see a panel/notification widget that would use the full screen height. Something like the (almost useless) Windows Action Center, but where one could put whatever widgets he wants.

I've tried to use a regular panel on the right side of screen with auto-hide but it's not usable because on every touch on the right side it shows up.

I think the solution would really be a button that would change the visibility of that panel on click (something like the activities button does).

The intention is that for notifications, clip areas, updates, (or whatever plasmoid/widget wanted), one could easily make use of the full screen height. :)

By the "_Full Notifications_" i was thinking this plasmoid would do that :)

**Comment by intika** [comment]
You mean you would want a resized notification panel to fill the whole screen in case there is a lot of notifications... that's a good idea, i will look into it for next version... 
Otherwise adding widgets etc to that panel like windows does is out of the scope of that fork a whole new plasmatoid would be needed to do that...

**Comment by intika** [comment]
here is a workaround for you you could add a system stray icon widget and in its option select the icons you want in it AND set them to always be hidden to have them all on a popup... now you would need to resize the popup size... so this would be a modified version of system tray plasmatoid i will have a look at this later i'll let you know but i promise nothing ;)

**Comment by intika** [comment]
okay, to achieve what you want we need to edit all the widget that use that pop window to make them act similar... 
first thing first for plasma-nm (network wifi...)
editing main.qml `Plasmoid.switchHeight` do the trick 
also need to be done on the clipbloard and the network... 
just making those edits i will post later may be update, i still did not reload plamashell to check it out may be editing everything wont be needed ...

**Comment by intika** [comment]
@maverick74  good news i found how to achieve what you want easily ^^ and actually use it my self :) 
1. first you need to add a new tray applet in the corner of your taskbar (the corner where you want the menu to be)
2. on the systray applet settings select what icons you wants (disable applications...) 
3. on systray applet settings / entry / set all icon to hidden 
4. edit that file `/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/ExpandedRepresentation.qml`
5. replace `Layout.minimumHeight: units.gridUnit * 21` by `Layout.minimumHeight: units.gridUnit * 21 * 2` or * 3 or whatever the length you want, i think there is a variable to use the whole screen size... 
6. disconnect and reconnect and voila :)

**Comment by maverick74** [comment]
Hi @intika 
I'm sorry, i don't get why but i didn't get any notifications about replies on this post (weird!).

My intentions was, if possible, a button that would more or less behave like the activities button does, but applied to a regular panel.

I was thinking of it like this: a regular button/plasmoid (that i, personally, would put on the right side of the clock plasmoid on the taskbar) that when we click on it, it would make a regular panel (placed whereever the user wants - in my case on the right side) to show up.

That panel - as any regular panel - can have on it any plasmoids.

Plasma, at the moment, already supports most of it. The problem is that, to achieve the "feel" i wish i have to set it to auto-hide, but most of the times i get to the scrollbar of a maximized window i touch the rightside of the screen and... "ups, there's the dawm sidepanel showing up". 

The solution would really be if it would open only when we click on something, like the button i suggested!!!

Comparing it to the solution you presented, this has the advantage we could place there whatever Plasmoids we want (e.g.: Calendar, Weather, Notifications, etc).

Still, could you post an image of the result you obtained?

( For reference, i also found this on the forum - however it's a bit limited: [https://forum.kde.org/viewtopic.php?f=285&t=139113](https://forum.kde.org/viewtopic.php?f=285&t=139113) )

**Comment by intika** [comment]
Yep i get you but it's require some work to get exactly exactly what you want...
But any way here is what i was talking about 

![screenshot_20180504_222144](https://user-images.githubusercontent.com/6892180/39651902-fb9c5236-4feb-11e8-9521-fd6237b2e54a.png)

![screenshot_20180504_222241](https://user-images.githubusercontent.com/6892180/39651904-fbcc4522-4feb-11e8-8a93-6cc790b614a0.png)

![screenshot_20180504_222312](https://user-images.githubusercontent.com/6892180/39651905-fbf53afe-4feb-11e8-82fe-9af1487e05ed.png)

**Comment by intika** [comment]
eventually post some capture with your current config i can may be help to find easy solution

**Comment by maverick74** [comment]
@intika This is an example i just made up. But it's actually unusable, since the only option is to have it touch activated and that's a real pain!
(side note: this **panel** occupies all my screen height from taskbar to top of screen)

![sidebar](https://user-images.githubusercontent.com/14912461/39697868-5f6a1398-51ea-11e8-8033-e8f8ca6f894b.png)

**Comment by intika** [comment]
okay i guess you want to open your panel only with a button and not with the mouse going to the side of the screen... 
i think i found a solution for your problem... have a look at this 
https://askubuntu.com/questions/396588/set-a-hotkey-to-show-an-auto-hiding-plasma-panel

**Comment by maverick74** [comment]
@intika 
Yes!!! It seems that would be it!!! (I was not able to find anything like this before)
Still, unfortunately there are two problems:

1. It's not for KDE5
2. and no easy way to get it (like using GHNS to get it)

Wouldn't you be interested it fork this (just asking... =P )??? Would be great :D

**Comment by intika** [comment]
@maverick74 
i just made a kwin script that toggle panel 

https://www.opendesktop.org/p/1266534/

We can also add more feature to a panel by setting it up in (KDE System Settings - Window Manager - Window Rules - New - Detect Window Properties "And select your pannel"

**Comment by maverick74** [comment]
@intika Great! Really happy with it! 

But when you say that it's a "hacky script to toggle the visibility of the panel by setting its size to a negative value" i wonder if there isn't a way to use/change the native plasma panel visibility settings?

I ask this because it sometimes "glinches" (panel seems to first appear on the leftside before moving to right). Also... a (all-in-one) widget where one could _choose_ the panel (instead of having to install the right one) would be a nice addition :)

Anyway, it does the job!!! Thank You! :D

**Comment by intika** [comment]
@maverick74 appearing in the opposite side for 50 millisecond before appearing in the normal side is what the code actually do so it's normal because this is the only way i found to make the panel popup otherwise just changing its size to negative/positive value does not make it pop up when the panel is set to autohide... 

there is a function that change the panel display from "autohide" to "always visible" or "covered by other window" but the function does not work, i guess it's a bug in kwin plasma framework it's why i did not use that function (at least the settings are not applied in real time).

kwin script are very very limited we even can not run classic bash script with kwin (at least not officially) we are just allowed to manipulate windows/plasma and even there it's limited, so it's the only way i found to make this work.

There is an open bug in the plasma bug channel that ask developer to make panel toggle available from the corner but it still not resolved... apparently the feature was available before in kde3 but was removed. 

About the widget idea yeah that would be cool, also with the widget framework code we could do mush more but it's a lot of work... a day or half a day and i don't really have the time to have it done... at least not for now... i will let you know here if i do something about it, but i promise nothing ;) as you say at least the current script does the job :) 

One last thing my kwin script code is very simple you can edit it to match your needs you can for example set your panel to always visible and remove the line where the code display the panel in the opposite side.

**Comment by maverick74** [comment]
Nice!!! :) Thank you.

A widget would be awesome. I'll keep an eye on this issue just in case you hit the jackpot and get a lot of free time. Ahah

I'll ask you just one more thing: can you please share the link to the plasma bug you mentioned?

**Comment by intika** [comment]
https://bugs.kde.org/show_bug.cgi?id=158556

**Comment by intika** [comment]
it's your lucky day ! 
i did not get a jackpot lol but i get the widget done with a lot of features :) 
https://www.opendesktop.org/p/1269113/
and https://github.com/intika/kdetogglepanel
hehe :) it took me a day but it's done ;)  Enjoy ! (you could even disable the flickering in the opposite side ;))
Donations are welcome hahahahaha

**Comment by maverick74** [comment]
@intika GREAT!!!

ok... first comments:

- (kind of important): Isn't there a way to have this working with panels locked???
- (not very important): Isn't there a way to set it to auto-hide after clicking "out of the panel"?

About the "visibility toggle" we spoke above, in a regular "panel" that is set to auto-hide itself, the approach of the screen edge by the mouse triggers the panel to show up (I suppose it sets it's visibility value to 1, while on getting off it sets the value to 0). 
- Isn't there a way to use that trigger in the widget? (not that, for my use this will be very important either... just curios about it :) )

About possible Bugs:
I've set a panel on the right side of the screen.
- Notifications are partially hidden/cut when the panel is hidden (possible do to it being set with a negative value... would setting it to 0 (zero) solve the problem? or maybe, if possible, use the trigger from the previous question?)

![bug](https://user-images.githubusercontent.com/14912461/47173933-445d5800-d307-11e8-8d1b-d529c4ad4cfb.png)

And i believe it's all :)

**Comment by maverick74** [comment]
@intika Sorry for the edits... just wanted to put it all in one post.

**Comment by intika** [comment]
> * (kind of important): Isn't there a way to have this working with panels locked???

Yes, but for a perfect working with panel locked kde plasma need to be at v5.13 or above, what version are you using ? (check it on kinfocenter) otherwise the only workaround is to set it to "Force unlock..." in advanced settings ... 

The widget unlock the panel and hide/unhide the panel then relock it if it was locked.

Classic method to lock/unlock : use the classic method to lock/unlock it's only compatible with plasma 5.13 and above (i did not test it tho because i am using 5.12) 

Here is what "Force unlock..." do : (hacky code) considering that the panel is locked... 
- This feature needs xdotool package
- The widget show the desktop 
- Then simulate the shortcut "alt+d, l" shortcut to lock/unlock the panel
- Restore desktop
- Hide/Unhide the panel 
- Relock the panel after 10 sec or after 1 sec depending on the settings 

> * (not very important): Isn't there a way to set it to auto-hide after clicking "out of the panel"?

Yes, you need to set your panel to autohide. in your panel settings (in this case you may need to enable the feature "force the panel to popup"

> About the "visibility toggle" we spoke above, in a regular "panel" that is set to auto-hide itself, the approach of the screen edge by the mouse triggers the panel to show up (I suppose it sets it's visibility value to 1, while on getting off it sets the value to 0).
> Isn't there a way to use that trigger in the widget? (not that, for my use this will be very important either... just curios about it :) )

If you want the exact same behavior as the screen edge script you need to setup the settings to :
- "Hide and auto-hide after 10 sec"
- "Force the panel to pop-up"
- "Use classic method to lock/unlock" (but the panel needs to be unlocked if not in v5.13)

> Notifications are partially hidden/cut when the panel is hidden (possible do to it being set with a negative value... would setting it to 0 (zero) solve the problem? or maybe, if possible, use the trigger from the previous question?) 

Yes this is because of the negative value... this does not happen when the panel is set to auto-hide... indeed setting the panel to 0 would solve the issue but it's very hard for the widget to remember what was the panel size before setting it to 0, i use the negative value because i just have to do (x * -1) every time to toggle the panel without saving/restoring it's size... i will see if i can do something for that... can you open an issue here https://github.com/intika/kdetogglepanel and follow there please ;)

**Comment by maverick74** [comment]
I'm on openSUSE Tumbleweed, so i'm on Plasma 5.14.

Still, i'm not at work and so, not on Linux ATM... Tomorrow will try your suggestion (either i didn't set it right or we have another bug).

I thought about open an issue there, but since we were already here...

Will open it right away :) See you there!
