### ISSUE TITLE
Change the color of the notifications icon when unread notifications

### ISSUE THREAD

**Issue by xakraz** [Intika-Linux-Plasmoid/plasmoid-notifications-full#2]
I don't know if it is the right place for this, but it would be nice if the notification icon turns red (by example) when there are unread notifications.

It will catch attention if you went away of your desk :)

**Comment by intika** [comment]
nice idea, i will look into that for the next version but i don't know when :)

**Comment by intika** [comment]
I just checked this as i am working on an update... 

For this feature, we would need to identify what's an "unread" notification, and it's somehow confusing... 

1. Notification can be all cleared by right-click...
2. New notification will always remain on the list until they are dismissed/removed 

As notifications are not automatically cleared, to be able to identify a notification as unread we would either mark notification as read or check the notification list (it require an action from the user anyway can not be easily automated because of the main function which is keeping notifications)

As it require an action from the user it would be simpler if we just clear notifications to make the action "mark as read" and new notification will be kept anyway. and this wont need a modification as it's already available, it's just a different way of usage. 

thus said the idea is not impossible it would just require some additional time to be implemented and my time for this addon is limited... (the solution would be watching for inactivity then mark any new notification as unread on inactivity and thus colorize the notification count)

This will be a wont fix for the moment, i will open back this issue if the situation change ;) 

a workaround is just to clear notifications list after checking them by right-clicking the plasmoid
